# Generated by Django 5.0 on 2023-12-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best_jewellery',
            name='about',
            field=models.CharField(max_length=250, verbose_name='About hndik'),
        ),
    ]
