# Generated by Django 5.0 on 2023-12-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_latest_products_header_latest_products_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='best_jewellery',
            name='about',
            field=models.TextField(verbose_name='About hndik'),
        ),
    ]
