# Generated by Django 5.0 on 2023-12-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_best_jewellery_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='About name')),
                ('button_name', models.CharField(max_length=50, verbose_name='Button name')),
                ('img', models.ImageField(upload_to='images', verbose_name='About img')),
                ('about', models.TextField(verbose_name='About text')),
            ],
        ),
    ]
